name: Terraform Apply
on:
  push:
    branches:
      - master

jobs:
  on-merged:
    name: On Push to master
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v1

    - name: Terraform - Init
      uses: hashicorp/terraform-github-actions/init@v0.3.7
      env:
        TF_ACTION_WORKING_DIR: "./aws_terraform"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Terraform - Apply
      uses: hashicorp/terraform-github-actions/apply@v0.3.7
      env:
        TF_ACTION_WORKING_DIR: "./aws_terraform"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
