name: Terraform Plan
on:
  pull_request:
    types: [opened, reopened, synchronize, rerequested]

jobs:
  on-pull-request:
    name: On Pull Request
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./aws_terraform
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v1

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-1

    - name: Terraform - Setup
      uses: hashicorp/setup-terraform@v1

    - name: Terraform - Format
      id: fmt
      run: terraform fmt
      continue-on-error: true

    - name: Terraform - Init
      id: init
      run: terraform init

    - name: Terraform - Validate
      id: validate
      run: terraform validate -no-color

    - name: Terraform - Plan
      id: plan
      run: terraform plan -no-color
